### ISSUE TITLE
Could you share me how to run the backend server command example ?

### ISSUE THREAD

**Issue by wade-liwei** [alexander171294/web-poker#18]
I just know a little about java, 
I have tried, but can not run it. so please help me .

Share me the full command about running the all backend service.

**Comment by wade-liwei** [comment]
I have wrote a dummy backend service with golang.

**Comment by alexander171294** [comment]
Hi, for developer purposes, open the project with eclipse (open eclipse, right click, import project, Maven Project) if you import the root of backend folder, you are importing all services, once you have imported the backend, right click in the next clases in order and press Run As -> Java Application:

Orchestrator: OrchestratorServer.java

ApiServer: ApiServer.java

Room Server: RoomServer.java

https://github.com/alexander171294/web-poker/blob/master/backend/orchestrator/src/main/java/ar/com/tandilweb/orchestrator/OrchestratorServer.java

https://github.com/alexander171294/web-poker/blob/master/backend/ApiServer/src/main/java/ar/com/tandilweb/ApiServer/ApiServer.java

https://github.com/alexander171294/web-poker/blob/master/backend/room/src/main/java/ar/com/tandilweb/room/RoomServer.java

Or if you wait to Alpha Release, you can run all using docker with only one command.
