### ISSUE TITLE
Backend in headless/docker mode

### ISSUE THREAD

**Issue by jason-s-yu** [alexander171294/web-poker#25]
Was wondering ifthere is a way to launch the backend from commandline/on a server in headless mode or with docker?
If there is any desire for a docker launch I could implement and PR.

EDIT: I read mentions of Docker in the readmes but found nothing for it?

**Comment by alexander171294** [comment]
Hi! my idea is make a docker image and upload to dockerhub when have a Alpha status version, right now the status of the code doesn't fulfill the basic functions then has not sense to create a image. In the future I make a docker image and instructions to deploy in a Kubernetes or Openshift orchestrator.

**Comment by r1yand** [comment]
For God's sake, I'm a beginner. may i have the installation video please. I promise to pray that God will bestow your sustenance 🙏🙏🙏

**Comment by toqen360** [comment]
Alexander..
Deseamos contratar tu servicios para implementar este repositorio.
Cómo podemos contactarte?

**Comment by alexander171294** [comment]
Hi!, we are working in new version of this web-poker, because this version was designed to be multi-game network, but that idea is too big for me, so I'm working in new version of web-poker from scratch simplifying all the idea.
