### ISSUE TITLE
replace backend with golang 

### ISSUE THREAD

**Issue by wade-liwei** [alexander171294/web-poker#27]
Hey guys

do you want to replace the backend  by golang.
then you can  implement frontend.

**Comment by wade-liwei** [comment]
Could you share me your real time account ?

**Comment by alexander171294** [comment]
Most of the hours dedicated to this project went to the backend, it is already solved and follows the protocol. 
Redoing it in another language could take another year of work and I don't see the advantage.

Why do you want to do it in golang?

**Comment by wade-liwei** [comment]
I want to integrate  encrypted currency into the game by golang.
and I do not know how to run the java backend server.

**Comment by wade-liwei** [comment]
like the game: https://virtue.poker/

**Comment by wade-liwei** [comment]
Thank you.

I will try it.

**Comment by wade-liwei** [comment]
there is no target for room service, So I replace the  " cd ../../room" with "cd ../room"
than run build.sh, but  errors happened.

please help me.

[INFO] ------------------------------------------------------------------------
[LIB] INSTALLING ROOM IMPLEMENTATION SUBSYSTEM
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /Users/a/go/src/github.com/alexander171294/web-poker/backend/room-poker/room-poker/pom.xml: only whitespace content allowed before start tag and not s (position: START_DOCUMENT seen s... @1:1)  @ line 1, column 1
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project  (/Users/a/go/src/github.com/alexander171294/web-poker/backend/room-poker/room-poker/pom.xml) has 1 error
[ERROR]     Non-parseable POM /Users/a/go/src/github.com/alexander171294/web-poker/backend/room-poker/room-poker/pom.xml: only whitespace content allowed before start tag and not s (position: START_DOCUMENT seen s... @1:1)  @ line 1, column 1 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
./build.sh: line 13: cd: ../room: No such file or directory
[PCKG] Building Generic Room
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /Users/a/go/src/github.com/alexander171294/web-poker/backend/room-poker/room-poker/pom.xml: only whitespace content allowed before start tag and not s (position: START_DOCUMENT seen s... @1:1)  @ line 1, column 1
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project  (/Users/a/go/src/github.com/alexander171294/web-poker/backend/room-poker/room-poker/pom.xml) has 1 error
[ERROR]     Non-parseable POM /Users/a/go/src/github.com/alexander171294/web-poker/backend/room-poker/room-poker/pom.xml: only whitespace content allowed before start tag and not s (position: START_DOCUMENT seen s... @1:1)  @ line 1, column 1 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
./build.sh: line 16: cd: ../orchestrator: No such file or directory
[PCKG] Building Orchestrator System
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /Users/a/go/src/github.com/alexander171294/web-poker/backend/room-poker/room-poker/pom.xml: only whitespace content allowed before start tag and not s (position: START_DOCUMENT seen s... @1:1)  @ line 1, column 1
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project  (/Users/a/go/src/github.com/alexander171294/web-poker/backend/room-poker/room-poker/pom.xml) has 1 error
[ERROR]     Non-parseable POM /Users/a/go/src/github.com/alexander171294/web-poker/backend/room-poker/room-poker/pom.xml: only whitespace content allowed before start tag and not s (position: START_DOCUMENT seen s... @1:1)  @ line 1, column 1 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
./build.sh: line 19: cd: ../ApiServer: No such file or directory
[PCKG] Building ApiServer Service.
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /Users/a/go/src/github.com/alexander171294/web-poker/backend/room-poker/room-poker/pom.xml: only whitespace content allowed before start tag and not s (position: START_DOCUMENT seen s... @1:1)  @ line 1, column 1
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project  (/Users/a/go/src/github.com/alexander171294/web-poker/backend/room-poker/room-poker/pom.xml) has 1 error
[ERROR]     Non-parseable POM /Users/a/go/src/github.com/alexander171294/web-poker/backend/room-poker/room-poker/pom.xml: only whitespace content allowed before start tag and not s (position: START_DOCUMENT seen s... @1:1)  @ line 1, column 1 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
Done all tasks, [LIB-EXCHANGE] [LIB-PERSISTENCE] [LIB-ROOM-INT] [PCKG-POKER-ROOM] [LIB-ROOM] [PCKG-ORCHESTRATOR] [PCKG-API-SERVER]

**Comment by alexander171294** [comment]
Srry, I push an "s" letter in dependency file by mistake, it's causing the errors.

Regarding this: "cd ../../room" is because 3 lines before I do "cd ../room-poker/room-poker".

Pull and try again please.

**Comment by wade-liwei** [comment]
Thanks, I will try it.

**Comment by wade-liwei** [comment]
start room service  with the following errors,
does it need the  file  /home/harkonidaz/lastHandshake.json ?


2020-04-28 12:14:47.566 ERROR 4229 --- [       Thread-1] a.c.t.r.o.processors.RoomAuthProcessor   : I/O Exception in processSignupResponseSchema

java.io.FileNotFoundException: /home/harkonidaz/lastHandshake.json (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method) ~[na:na]
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298) ~[na:na]
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[na:na]
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187) ~[na:na]
	at com.fasterxml.jackson.core.JsonFactory.createGenerator(JsonFactory.java:1195) ~[jackson-core-2.9.5.jar!/:2.9.5]
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3160) ~[jackson-databind-2.9.10.4.jar!/:2.9.10.4]
	at ar.com.tandilweb.room.orchestratorBridge.processors.RoomAuthProcessor.processSignupResponseSchema(RoomAuthProcessor.java:49) ~[classes!/:0.0.1]
	at ar.com.tandilweb.room.orchestratorBridge.OrchestratorThread.roomAuthProcessorSelector(OrchestratorThread.java:169) ~[classes!/:0.0.1]
	at ar.com.tandilweb.room.orchestratorBridge.OrchestratorThread.processSchema(OrchestratorThread.java:153) ~[classes!/:0.0.1]
	at ar.com.tandilweb.room.orchestratorBridge.OrchestratorThread.processIncommingMessage(OrchestratorThread.java:148) ~[classes!/:0.0.1]
	at ar.com.tandilweb.room.orchestratorBridge.OrchestratorThread.main(OrchestratorThread.java:120) ~[classes!/:0.0.1]
	at ar.com.tandilweb.room.orchestratorBridge.OrchestratorThread.run(OrchestratorThread.java:87) ~[classes!/:0.0.1]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

**Comment by wade-liwei** [comment]
frontEnd  can not join the default room, and prompt:  "CONNECTING TO SERVER  Last validation"

how to join the room and create a new room ?

**Comment by wade-liwei** [comment]
how to fix the problem ?

------------------>  - - - - >{Receiving} {"endpoint":"/userInterceptor/AuthController/rejected","data":{"protocol":"eppr/sn","version":"1.0.0","namespace":"eppr/user-auth","schema":"rejected"}}
room.component.ts:36 []> @RoomServer >> UserAuth Rejected

**Comment by wade-liwei** [comment]
I have it on the public IP, http://149.129.58.127:4000/
Could you please tell me how to create a room or join a room.

**Comment by wade-liwei** [comment]
room  start error :

2020-04-28 19:06:22.639 ERROR 6682 --- [       Thread-1] a.c.t.r.o.OrchestratorThread             : Connection IO Exception, 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:608) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:557) ~[na:na]
	at java.base/java.net.Socket.<init>(Socket.java:453) ~[na:na]
	at java.base/java.net.Socket.<init>(Socket.java:230) ~[na:na]
	at ar.com.tandilweb.room.orchestratorBridge.OrchestratorThread.createSocketConneciton(OrchestratorThread.java:131) ~[classes!/:0.0.1]
	at ar.com.tandilweb.room.orchestratorBridge.OrchestratorThread.run(OrchestratorThread.java:82) ~[classes!/:0.0.1]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2020-04-28 19:06:22.787 ERROR 6682 --- [       Thread-1] a.c.t.r.o.OrchestratorThread             : Socket read Error

java.lang.NullPointerException: null
	at ar.com.tandilweb.room.orchestratorBridge.OrchestratorThread.sendDataToServer(OrchestratorThread.java:140) ~[classes!/:0.0.1]
	at ar.com.tandilweb.room.orchestratorBridge.OrchestratorThread.main(OrchestratorThread.java:115) ~[classes!/:0.0.1]
	at ar.com.tandilweb.room.orchestratorBridge.OrchestratorThread.run(OrchestratorThread.java:87) ~[classes!/:0.0.1]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

Exception in thread "Thread-1" java.lang.NullPointerException
	at ar.com.tandilweb.room.orchestratorBridge.OrchestratorThread.run(OrchestratorThread.java:92)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by wade-liwei** [comment]
I suggest you create a docker compose when you are free.

**Comment by alexander171294** [comment]
Hi!, any room is an instance connected to Orchestrator, if you want to start a new room, you need to configure and run another instance of room server. If you want to know more about the implementation and design, you can read the definition doc: https://docs.google.com/document/d/1gBXpZ4h8RLj_pJVv9hG6ApM5y0AJc0k10xR1c9yYKWg/edit

Related to docker please read this pinned issue:
https://github.com/alexander171294/web-poker/issues/25

Actually, the game is in pre-Alpha, isn't a fully playable version. The flags --prod and some basic functionallities aren't available.

Related to UserAuth Rejected, according to RFC (definition doc previously writen),  

Page 12:
```
Protocol: User-Auth
Schema: Rejected
eppr/user-auth::rejected
```

> This schema is used for alert to client that the challenge isn’t match with the indicated by the user in the challenge request, is it, the response of backward-validation not match with the request of authorization.

I think you has a misconfiguration in orchestrator/room/client.

I recommend you wait for an Alpha version release with docker and guide for run/configurations.

Thanks for reading.

**Comment by wade-liwei** [comment]
got it.
Thanks a lot.

**Comment by alexander171294** [comment]
If you wait near the end of the year, I think I will release an Alpha version.

**Comment by wade-liwei** [comment]
In China, the speed is very slow,
Right now, I am not sure I can wait near the end of the year, maybe I will give up.

Look forward to the game.

**Comment by alexander171294** [comment]
I do my best effort, but I work full time, and i have another side project (a strategy game for android), and can't spend much time in finish this before end of year.

Thanks for reading, If you want to rewrite the backend in golang, you can follow RFC for frontend compatibility (you need to use StompJS).

Pd: I'm from Argentina :)

**Comment by alexander171294** [comment]
I check yout link:
http://149.129.58.127:4000/

And I think you didn't start the ApiServer, I can't signup (net::ERR_CONNECTION_REFUSED) the ApiServer is a crucial part of room connection because make a Security signup using rest JWT.

You can't access directly to room without login for security reasons.

**Comment by wade-liwei** [comment]
I do my best effort, but I work full time, and i have another side project (a strategy game for android), and can't spend much time in finish this before end of year.

Thanks for reading, If you want to rewrite the backend in golang, you can follow RFC for frontend compatibility (you need to use StompJS).

Pd: I'm from Argentina :)


ok, I will share you my decision after read your RFC.
