### ISSUE TITLE
Setup environment

### ISSUE THREAD

**Issue by taieb92** [alexander171294/web-poker#32]
Hello,

I am trying to deploy the game on my local machine. I could make it up and running and create and user and login. But I couldnt join a table. Everytime I try to join the automatically. created table I get Connecting to server message and nothing happens. Here a screenshot
<img width="1524" alt="Screenshot 2020-05-01 at 11 48 10" src="https://user-images.githubusercontent.com/11615168/80797614-9771c580-8ba2-11ea-87ce-61cfb16210b8.png">

Can you give me more insights about the topic?

**Comment by taieb92** [comment]
I also see in the room logs 

> INFO 54223 --- [MessageBroker-8] a.c.tandilweb.room.handlers.GameHandler  : [Room Monitor] Users in table: [null,null,null,null,null,null,null,null,null,null]

Maybe it has something to do with the issue

**Comment by wade-liwei** [comment]
@taieb92 

the same problem for me.
Do you want to write codes for the project ?
If you are good at angular, I can rewrite the backend.

**Comment by taieb92** [comment]
I didnt go too deep in the code but it looks to me in a good state. just some bug fixing is needed. Why do you think that it makes sense to rewrite the BE?

This exact issue is happening in the BackwardValidation step. The user data and data response are null and it crashes with a null pointer exception. I added the null validation but it doesnt help. I dont get it why the user data is null in that case

**Comment by alexander171294** [comment]
Hi!, I think something is wrong with clean startup, maybe is the database migration or something like this, let me check tomorrow when I have time.

Thanks for the info, I will try to reproduce the error.

**Comment by taieb92** [comment]
I am trying to fix it as well. I saw that you are aware of it as you wrote a fix me comment next to the bug.
looks like the game is working for you. Is there a work around to make it work currently for me so that i can try a full game?
I have it installed locally from the command line

**Comment by wade-liwei** [comment]
Why do you think that it makes sense to rewrite the BE?

because of I just know a little about  JAVA and I want to integrate it with blockchain.
I am a golang developer.

**Comment by alexander171294** [comment]
Hi!, we push around 200 commits, I think the bug is fixed, please retry.

**Comment by wade-liwei** [comment]
Got it, I will try.

Thank you so much.

**Comment by wade-liwei** [comment]
same problem happen

**Comment by alexander171294** [comment]
try with this link: http://web-poker.tandilserver.com/

**Comment by wade-liwei** [comment]
I can not access the URL:  http://web-poker.tandilserver.com/ ;
Could you please share me your other chat account, I will share you my server login.
Please help me setup the  poker server.

**Comment by hardikjain29** [comment]
@taieb92 - Stuck at the same thing. Were you able to figure something out?

**Comment by alexander171294** [comment]
kardikjain29
Are you running using docker?

https://github.com/alexander171294/web-poker/wiki/Docker-Getting-Started

Check your database, if exists and check if flyway has created the tables

**Comment by hardikjain29** [comment]
![image](https://user-images.githubusercontent.com/13768932/87251462-95bd5b80-c489-11ea-9b3d-119ff6854b5e.png)
![image](https://user-images.githubusercontent.com/13768932/87251467-9bb33c80-c489-11ea-8e86-534f803f3519.png)

Yes @alexander171294, I have done through the process in the docker wiki. Attached the table values for rooms.

Also, I have started the room-poker container on 8085 and made code changes too. Could it be because of this?

**Comment by hardikjain29** [comment]
The connection is made to the room-poker, otherwise it says `An error occurred, disconnected from server, the page reload in 5 seconds.` but it's stuck at `'Last validation.` nothing happens after that.

**Comment by alexander171294** [comment]
It can be, please share me your F12 console and networks calls.

**Comment by hardikjain29** [comment]
![image](https://user-images.githubusercontent.com/13768932/87252160-94426200-c48e-11ea-8461-4bc0da1c9362.png)
![image](https://user-images.githubusercontent.com/13768932/87252185-b3d98a80-c48e-11ea-9173-61161aefa29f.png)
![image](https://user-images.githubusercontent.com/13768932/87252199-ca7fe180-c48e-11ea-97bc-9270698fb887.png)
![image](https://user-images.githubusercontent.com/13768932/87252209-d2d81c80-c48e-11ea-8f20-46e01c9ab79c.png)

**Comment by alexander171294** [comment]
You can upload logs of docker logs (Room and Orchestrator logs).

https://docs.docker.com/engine/reference/commandline/logs/

**Comment by wade-liwei** [comment]
how's going with the problem ?
