### ISSUE TITLE
Full Design

### ISSUE THREAD

**Issue by aronprins** [alexander171294/web-poker#4]
Hey,

Do you have the full design ready for this project as shown in the photos shown in html/css?

Very interested in a copy.

Cheers,
Aron

**Comment by alexander171294** [comment]
srry but, i'm creating the html/css according to the needs of the project.

This is the full design concept:

https://github.com/alexander171294/web-poker/blob/master/frontend/concepts/poker_pres_3.png

This is from dribbble but i can't find the author.

Eberle Alexander.-
