### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by nnmix** [alexander171294/web-poker#5]
hi alexander, i hope all is well, what's the newest update about the project, i have a suggestion and trying to contact you, please let me know. thanks

**Comment by alexander171294** [comment]
Hi!, thanks for your interest, but right now the game is not completed, the most updated version is in this branch:

https://github.com/alexander171294/web-poker/tree/eppr-sn

We are working for finish the project, but as the readme say:

"I hope this project end in one moment of the universe history."
